### ISSUE TITLE
两个同级div是否会同时接收到鼠标事件呢？

### ISSUE THREAD

**Issue by wilhantian** [BentleyBlanks/TattyUI#1]

**Comment by BentleyBlanks** [comment]
抱歉回复晚了

您意思的同级是指[1]

> <div name="0">
>       <div name="1" />
>       <div name="2" />
> </div>

或者是[2]

> <div name="1">
>      <div name="2" />
> </div>

描述的是哪个1和2的同级的意思？

我这里确定的机制是这样的

> 若父节点收到消息 那么会将此事件分发给其所有的子节点。

比如这里的0会分发给1和2，但12彼此互相不影响。具体实现在t2DivController::onXXXX()中可以直观的看到。

如果想要直观的测试的话可以在html.h(已更新)中将导入的html文件改为index-1.html即可，其中的div4会在root状态hover时改变自身background-color。

> 说实话……没想到有人会看到TattyUI。因此如果有找到BUG或者是改进建议，希望能反馈给我。

2016-02-26 10:57 GMT+08:00 WilhanTian 田伟汉 notifications@github.com:
